version: '3'
services:
  web:
    container_name: django
    build: ./dockerfiles/django
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000

  front:
    container_name: vue3
    build: ./dockerfiles/vue3
    volumes:
      - ./django/app:/code
    ports:
      - "8080:8080"
    tty: true
